http:
#servers:
- listen_on: 80
  routers:
  - location: /a
    proxy:
    - ip: http://localhost:8081
      weight: 1
    - ip: http://localhost:8082
      weight: 2
    balancer: WeightRandom
  - location: /fs
    balancer: ConsistentHash
    root: ./test
    index: index.html